# Generated by Django 5.2.8 on 2026-05-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Optional personal note about this wishlist item.'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
