# Generated by Django 5.2.8 on 2025-11-13 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('off_percent', models.IntegerField(blank=True, default=0)),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('sku', models.CharField(max_length=255)),
                ('category', models.ForeignKey(default='Universal', on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('tag', models.ForeignKey(default='Martify', on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
            ],
        ),
    ]
