# Generated by Django 5.2.8 on 2025-11-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_secondry',
            field=models.ImageField(blank=True, upload_to='uploads/product/'),
        ),
    ]
