# Generated by Django 5.2.8 on 2025-11-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_image_secondry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_secondry',
            field=models.ImageField(blank=True, default='../static/assets/images/no-image.jpg', upload_to='uploads/product/'),
        ),
    ]
