# Generated by Django 5.2.8 on 2025-11-14 05:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_image_alter_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_body', models.TextField(blank=True)),
                ('author', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.date.today)),
                ('category', models.ForeignKey(default='Universal', on_delete=django.db.models.deletion.CASCADE, to='core.blogcategory')),
            ],
        ),
    ]
