# Generated by Django 5.2.8 on 2025-11-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blogcategory_product_description_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='uploads/product/no-image.jpg', upload_to='uploads/blog/'),
        ),
    ]
