# Generated by Django 5.2.8 on 2025-11-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blog_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
