# Generated by Django 5.2.8 on 2025-11-14 09:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_body', models.TextField(blank=True)),
                ('author', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='uploads/product/no-image.jpg', upload_to='uploads/blog/')),
                ('created_at', models.DateTimeField(default=datetime.date.today)),
                ('category', models.ForeignKey(default='Universal', on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory')),
            ],
        ),
    ]
