# Generated by Django 5.2.8 on 2026-05-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='cod', help_text='Payment method used: cod, card, apps', max_length=50),
        ),
    ]
